// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'description': string;
  'header': string;
  'icon': string;
  'main': string;
  'toggle': string;
}
declare const cssExports: CssExports;
export = cssExports;
