// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottomMenu': string;
  'logo': string;
  'main': string;
  'menu': string;
  'menuActive': string;
  'panel': string;
  'sidebar': string;
  'wrapper': string;
}
declare const cssExports: CssExports;
export = cssExports;
